// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Code        string `json:"code"`
	Description string `json:"description"`
	Quantity    int    `json:"quantity"`
	UserID      int    `json:"user_id"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Product struct {
	ID          int    `json:"id"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Quantity    int    `json:"quantity"`
	UserID      int    `json:"user_id"`
}

type ProductMutation struct {
	Create *Product `json:"create"`
	Update string   `json:"update"`
	Delete string   `json:"delete"`
}

type ProductQuery struct {
	Product  *Product   `json:"product"`
	Products []*Product `json:"products"`
}

type UpdateProduct struct {
	Code        *string `json:"code"`
	Description *string `json:"description"`
	Quantity    *int    `json:"quantity"`
	UserID      int     `json:"user_id"`
}

type UpdateUser struct {
	Name  *string `json:"name"`
	Email *string `json:"email"`
}

type User struct {
	ID       int        `json:"id"`
	Name     string     `json:"name"`
	Email    string     `json:"email"`
	Password string     `json:"password"`
	Products []*Product `json:"products"`
}

type UserOps struct {
	Create *User  `json:"create"`
	Update string `json:"update"`
	Delete string `json:"delete"`
}

type UserQuery struct {
	User  *User   `json:"user"`
	Users []*User `json:"users"`
}
